################################################################################
#
# Astrologer
#
#####################
#
# Create Astrologer
#
#####################
astrologer_create:
    path: /astrologer
    controller: App\Controller\AstrologerServiceController::createAstrologer
    methods: POST
#####################
#
# Get Astrologer
#
#####################
astrologer_get:
    path: /astrologer/{id}
    controller: App\Controller\AstrologerServiceController::getAstrologer
    methods: GET
#####################
#
# Get Astrologers
#
#####################
astrologers_get:
    path: /astrologers
    controller: App\Controller\AstrologerServiceController::getAstrologers
    methods: GET
#####################
#
# Delete Astrologer
#
#####################
astrologer_delete:
    path: /astrologer/{id}
    controller: App\Controller\AstrologerServiceController::deleteAstrologer
    methods: DELETE
#####################
#
# Add Service to Astrologer
#
#####################
astrologer_service_add:
    path: /astrologer/{astrologerId}/service/{serviceId}
    controller: App\Controller\AstrologerServiceController::addServiceToAstrologer
    methods: POST
#####################
#
# Update Astrologer's Image
#
#####################
astrologer_image_update:
    path: /astrologer/{id}/image
    controller: App\Controller\AstrologerServiceController::updateAstrologerImage
    methods: POST
#####################
#
# Update Astrologer Service
#
#####################
astrologer_service_update:
    path: /astrologer/{astrologerId}/service/{serviceId}
    controller: App\Controller\AstrologerServiceController::updateAstrologerService
    methods: PATCH
#####################
#
# Delete Astrologer Service
#
#####################
astrologer_service_delete:
    path: /astrologer/{astrologerId}/service/{serviceId}
    controller: App\Controller\AstrologerServiceController::deleteAstrologerService
    methods: DELETE
#####################
#
# Get Astrologer Services
#
#####################
astrologer_services_get:
    path: /astrologer/{id}/services
    controller: App\Controller\AstrologerServiceController::getAstrologerServices
    methods: GET
#####################
#
# Get Astrologers Services
#
#####################
astrologers_services_get:
    path: /astrologers/services
    controller: App\Controller\AstrologerServiceController::getAstrologersServices
    methods: GET


################################################################################
#
# Service
#
#####################
#
# Create Service
#
#####################
service_create:
    path: /service
    controller: App\Controller\AstrologerServiceController::createService
    methods: POST
#####################
#
# Get Service
#
#####################
service_get:
    path: /service/{id}
    controller: App\Controller\AstrologerServiceController::getService
    methods: GET
#####################
#
# Get Services
#
#####################
services_get:
    path: /services
    controller: App\Controller\AstrologerServiceController::getServices
    methods: GET
#####################
#
# Delete Service
#
#####################
service_delete:
    path: /service/{id}
    controller: App\Controller\AstrologerServiceController::deleteService
    methods: DELETE


################################################################################
#
# Order
#
#####################
#
# Create Order
#
#####################
order_create:
    path: /order
    controller: App\Controller\OrderController::createOrder
    methods: POST
